# Generated by Django 2.2.5 on 2020-01-06 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=50)),
                ('cust_email', models.EmailField(default='na', max_length=254)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
